// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PE3.Data;

namespace PE3.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20190520084448_ClassRoom")]
    partial class ClassRoom
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PE3.Entities.ClassRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountOfPupils");

                    b.Property<long>("TeacherId");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new { Id = 1L, AmountOfPupils = 0, TeacherId = 1L },
                        new { Id = 2L, AmountOfPupils = 0, TeacherId = 2L },
                        new { Id = 3L, AmountOfPupils = 10, TeacherId = 3L }
                    );
                });

            modelBuilder.Entity("PE3.Entities.Pupil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate");

                    b.Property<long?>("ClassRoomId");

                    b.Property<int>("CurrentLevel");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<long?>("TeacherId");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Pupils");

                    b.HasData(
                        new { Id = 1L, Birthdate = new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Jonas", LastName = "Wouters" },
                        new { Id = 2L, Birthdate = new DateTime(2010, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Henk", LastName = "Verweer" },
                        new { Id = 3L, Birthdate = new DateTime(2009, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Emma", LastName = "Verdonck" },
                        new { Id = 4L, Birthdate = new DateTime(2010, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Chloe", LastName = "Pashalis" },
                        new { Id = 5L, Birthdate = new DateTime(2010, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Amelia", LastName = "Armstrong" },
                        new { Id = 6L, Birthdate = new DateTime(2009, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Nick", LastName = "Vermeersch" },
                        new { Id = 7L, Birthdate = new DateTime(2010, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "John", LastName = "Crombez" },
                        new { Id = 8L, Birthdate = new DateTime(2010, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Erik", LastName = "Braet" },
                        new { Id = 9L, Birthdate = new DateTime(2010, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Lily", LastName = "Peeters" },
                        new { Id = 10L, Birthdate = new DateTime(2010, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Pieter-Paul", LastName = "Pruim" }
                    );
                });

            modelBuilder.Entity("PE3.Entities.PupilRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ClassRoomId");

                    b.Property<long>("PupilId");

                    b.Property<DateTime>("SignedUpDate");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("PupilId");

                    b.ToTable("PupilRegistrations");
                });

            modelBuilder.Entity("PE3.Entities.Questions", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer");

                    b.Property<long>("ClassRoomId");

                    b.Property<int>("Level");

                    b.Property<string>("Question");

                    b.HasKey("QuestionId");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Questions");

                    b.HasData(
                        new { QuestionId = 1L, Answer = "", ClassRoomId = 1L, Level = 1, Question = "" },
                        new { QuestionId = 2L, Answer = "", ClassRoomId = 2L, Level = 1, Question = "" },
                        new { QuestionId = 3L, Answer = "273", ClassRoomId = 3L, Level = 1, Question = "De dierentuin koopt een viertal nieuwe vissoorten voor in het grote aquarium. Ze kopen 123 goudvissen, 18 kogelvissen, 55 maanvissen en 77 koperzalmen. Hoeveel vissen kocht de dierentuin in totaal?" },
                        new { QuestionId = 4L, Answer = "728", ClassRoomId = 3L, Level = 1, Question = "In de dierentuin wordt er ook heel wat voedsel voor de dieren aangekocht. Zo werd er deze week 275kg vlees voor de leeuwen, 148kg vogelzaad en 305kg noten geleverd. Hoeveel kg voedsel werd in totaal geleverd?" },
                        new { QuestionId = 5L, Answer = "230", ClassRoomId = 3L, Level = 1, Question = "Hoeveel is 10 x 23?" },
                        new { QuestionId = 6L, Answer = "298", ClassRoomId = 3L, Level = 1, Question = "900 min 702 is?" },
                        new { QuestionId = 7L, Answer = "89", ClassRoomId = 3L, Level = 1, Question = "Hoeveel is 130 - 41?" },
                        new { QuestionId = 8L, Answer = "10", ClassRoomId = 3L, Level = 1, Question = "100 : 10 =" },
                        new { QuestionId = 9L, Answer = "900", ClassRoomId = 3L, Level = 1, Question = "Hoeveel is 100 x 9?" },
                        new { QuestionId = 10L, Answer = "748", ClassRoomId = 3L, Level = 1, Question = "429 plus 319 is?" },
                        new { QuestionId = 11L, Answer = "500", ClassRoomId = 3L, Level = 1, Question = "10 x 50 =" },
                        new { QuestionId = 12L, Answer = "0", ClassRoomId = 3L, Level = 1, Question = "0 x 0 =" },
                        new { QuestionId = 13L, Answer = "56", ClassRoomId = 3L, Level = 2, Question = "De directeur van een school betaalt een uitstap: voor het vierde leerjaar betaalt hij 243 euro en voor het derde leerjaar betaalt hij 187 euro. Hoeveel kost de uitstap van het derde leerjaar minder dan die van het vierde leerjaar?" },
                        new { QuestionId = 14L, Answer = "1", ClassRoomId = 3L, Level = 2, Question = "50 : 50 =" },
                        new { QuestionId = 15L, Answer = "100", ClassRoomId = 3L, Level = 2, Question = "1000 : 10 =" },
                        new { QuestionId = 16L, Answer = "640", ClassRoomId = 3L, Level = 2, Question = "Hoeveel is 80 x 8?" },
                        new { QuestionId = 17L, Answer = "6", ClassRoomId = 3L, Level = 2, Question = "300 : 50 =" },
                        new { QuestionId = 18L, Answer = "45", ClassRoomId = 3L, Level = 2, Question = "450 : 10 =" },
                        new { QuestionId = 19L, Answer = "901", ClassRoomId = 3L, Level = 2, Question = "Hoeveel is 502 + 399?" },
                        new { QuestionId = 20L, Answer = "110", ClassRoomId = 3L, Level = 2, Question = "11 x 10 = " },
                        new { QuestionId = 21L, Answer = "899", ClassRoomId = 3L, Level = 2, Question = "Bereken de som van 576 en 249 en 74." },
                        new { QuestionId = 22L, Answer = "560", ClassRoomId = 3L, Level = 2, Question = "56 x 10" },
                        new { QuestionId = 23L, Answer = "364", ClassRoomId = 3L, Level = 3, Question = "Het derde en vierde leerjaar van Basisschool 'De Springplank' uit Brugge gaan met de bus op uitstap naar de Zoo van Antwerpen. Het derde leerjaar gaat op maandag naar de dierentuin en het vierde leerjaar gaat op dinsdag. De afstand van Brugge naar Antwerpen is 91km. Hoeveel km moet de bus in het totaal afleggen om het derde en het vierde leerjaar 's ochtends naar de dierentuin en 's avonds terug naar de school te brengen?" },
                        new { QuestionId = 24L, Answer = "70", ClassRoomId = 3L, Level = 3, Question = "Stephan de olifant is een reusachtig beest en heeft per week veel voedsel nodig. Stephan eet 210kg voedsel per dag. De opzichter geeft Stephan drie keer per dag evenveel eten. Hoeveel kg voedsel is dit per keer?" },
                        new { QuestionId = 25L, Answer = "9", ClassRoomId = 3L, Level = 3, Question = "180 : 20 =" },
                        new { QuestionId = 26L, Answer = "243", ClassRoomId = 3L, Level = 3, Question = "Trek 208 af van 451." },
                        new { QuestionId = 27L, Answer = "500", ClassRoomId = 3L, Level = 3, Question = "1000 : 2 =" },
                        new { QuestionId = 28L, Answer = "104", ClassRoomId = 3L, Level = 3, Question = "Zoek het verschil tussen 1000 en 896." },
                        new { QuestionId = 29L, Answer = "870", ClassRoomId = 3L, Level = 3, Question = "10 x 87 =" },
                        new { QuestionId = 30L, Answer = "160", ClassRoomId = 3L, Level = 3, Question = "8 x 20 =" },
                        new { QuestionId = 31L, Answer = "10", ClassRoomId = 3L, Level = 3, Question = "1000 : 100 =" },
                        new { QuestionId = 32L, Answer = "630", ClassRoomId = 3L, Level = 3, Question = "9 x 70 =" },
                        new { QuestionId = 33L, Answer = "5", ClassRoomId = 3L, Level = 4, Question = "Wat is de rest bij de deling 285:8?" },
                        new { QuestionId = 34L, Answer = "2", ClassRoomId = 3L, Level = 4, Question = "Wat is de rest bij de deling 849:7?" },
                        new { QuestionId = 35L, Answer = "280", ClassRoomId = 3L, Level = 4, Question = "70 x 4 =" },
                        new { QuestionId = 36L, Answer = "50", ClassRoomId = 3L, Level = 4, Question = "450 : 9 =" },
                        new { QuestionId = 37L, Answer = "72", ClassRoomId = 3L, Level = 4, Question = "Hoeveel is 12 x 6?" },
                        new { QuestionId = 38L, Answer = "70", ClassRoomId = 3L, Level = 4, Question = "280 : 4 =" },
                        new { QuestionId = 39L, Answer = "836", ClassRoomId = 3L, Level = 4, Question = "De termen zijn 238 en 598. Wat is de som?" },
                        new { QuestionId = 40L, Answer = "300", ClassRoomId = 3L, Level = 4, Question = "60 x 5 =" },
                        new { QuestionId = 41L, Answer = "810", ClassRoomId = 3L, Level = 4, Question = "90 x 9 =" },
                        new { QuestionId = 42L, Answer = "200", ClassRoomId = 3L, Level = 4, Question = "5 x 40" },
                        new { QuestionId = 43L, Answer = "", ClassRoomId = 3L, Level = 5, Question = "In circus Pipo treden elke week enkele dieren op. De directeur van het circus heeft 4 boxen met telkens 3 slangen, 3 stallen met telkens 1 paard, 2 wagons met telkens 2 kamelen, 5 houten boxen met telkens 3 duiven, 6 kooien met telkens 4 konijnen en 3 hokken met telkens 1 olifant. Hoeveel dieren telt het circus Pipo?" },
                        new { QuestionId = 44L, Answer = "192", ClassRoomId = 3L, Level = 5, Question = "Vorige maand kwamen er 768 bezoekers naar het circus. Circus Pipo was die maand vier weken open. Iedere week kwamen er evenveel bezoekers. Hoeveel bezoekers waren dit per week?" },
                        new { QuestionId = 45L, Answer = "112", ClassRoomId = 3L, Level = 5, Question = "448 : 4 =" },
                        new { QuestionId = 46L, Answer = "0", ClassRoomId = 3L, Level = 5, Question = "800 x 0 =" },
                        new { QuestionId = 47L, Answer = "6", ClassRoomId = 3L, Level = 5, Question = "420 : 70 =" },
                        new { QuestionId = 48L, Answer = "279", ClassRoomId = 3L, Level = 5, Question = "Hoeveel is 565 - 286?" },
                        new { QuestionId = 49L, Answer = "828", ClassRoomId = 3L, Level = 5, Question = "207 x 4 =" },
                        new { QuestionId = 50L, Answer = "80", ClassRoomId = 3L, Level = 5, Question = "480 : 6" },
                        new { QuestionId = 51L, Answer = "508", ClassRoomId = 3L, Level = 5, Question = "127 x 4 =" },
                        new { QuestionId = 52L, Answer = "231", ClassRoomId = 3L, Level = 5, Question = "693 : 3 =" }
                    );
                });

            modelBuilder.Entity("PE3.Entities.Results", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PupilAnswer");

                    b.Property<long>("PupilId");

                    b.Property<long>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("PupilId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("PE3.Entities.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new { Id = 1L, FirstName = "Dirk", LastName = "Vandenbroucke", Login = "dvandenbroucke", Password = "teacher" },
                        new { Id = 2L, FirstName = "Evan", LastName = "Dierickx", Login = "edierickx", Password = "teacher" },
                        new { Id = 3L, FirstName = "Sam", LastName = "Verkeyen", Login = "sverkeyen", Password = "teacher" },
                        new { Id = 4L, FirstName = "Erika", LastName = "Berends", Login = "eberends", Password = "teacher" },
                        new { Id = 5L, FirstName = "Sarah", LastName = "Cramers", Login = "scramers", Password = "teacher" }
                    );
                });

            modelBuilder.Entity("PE3.Entities.ClassRoom", b =>
                {
                    b.HasOne("PE3.Entities.Teacher", "Teacher")
                        .WithOne("ClassRoom")
                        .HasForeignKey("PE3.Entities.ClassRoom", "TeacherId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PE3.Entities.Pupil", b =>
                {
                    b.HasOne("PE3.Entities.ClassRoom")
                        .WithMany("Pupils")
                        .HasForeignKey("ClassRoomId");

                    b.HasOne("PE3.Entities.Teacher")
                        .WithMany("Pupils")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("PE3.Entities.PupilRegistration", b =>
                {
                    b.HasOne("PE3.Entities.ClassRoom", "ClassRoom")
                        .WithMany()
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PE3.Entities.Pupil", "Pupil")
                        .WithMany()
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PE3.Entities.Questions", b =>
                {
                    b.HasOne("PE3.Entities.ClassRoom", "ClassRoom")
                        .WithMany()
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PE3.Entities.Results", b =>
                {
                    b.HasOne("PE3.Entities.Pupil")
                        .WithMany("Results")
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PE3.Entities.Questions")
                        .WithMany("Results")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
