// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PE3.Data;

namespace PE3.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20190513141918_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PE3.Entities.ClassRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountOfPupils");

                    b.Property<long>("TeacherId");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.ToTable("ClassRooms");
                });

            modelBuilder.Entity("PE3.Entities.Pupil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate");

                    b.Property<long?>("ClassRoomId");

                    b.Property<int>("CurrentLevel");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<long?>("TeacherId");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Pupils");

                    b.HasData(
                        new { Id = 1L, Birthdate = new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Jonas", LastName = "Wouters" },
                        new { Id = 2L, Birthdate = new DateTime(2010, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Henk", LastName = "Verweer" },
                        new { Id = 3L, Birthdate = new DateTime(2009, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Emma", LastName = "Verdonck" },
                        new { Id = 4L, Birthdate = new DateTime(2010, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Chloe", LastName = "Pashalis" },
                        new { Id = 5L, Birthdate = new DateTime(2010, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Amelia", LastName = "Armstrong" },
                        new { Id = 6L, Birthdate = new DateTime(2009, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Nick", LastName = "Vermeersch" },
                        new { Id = 7L, Birthdate = new DateTime(2010, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "John", LastName = "Crombez" },
                        new { Id = 8L, Birthdate = new DateTime(2010, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Erik", LastName = "Braet" },
                        new { Id = 9L, Birthdate = new DateTime(2010, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Lily", LastName = "Peeters" },
                        new { Id = 10L, Birthdate = new DateTime(2010, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), CurrentLevel = 1, FirstName = "Pieter-Paul", LastName = "Pruim" }
                    );
                });

            modelBuilder.Entity("PE3.Entities.PupilRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ClassRoomId");

                    b.Property<long>("PupilId");

                    b.Property<DateTime>("SignedUpDate");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("PupilId");

                    b.ToTable("PupilRegistrations");
                });

            modelBuilder.Entity("PE3.Entities.Questions", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer");

                    b.Property<long>("ClassRoomId");

                    b.Property<int>("Level");

                    b.Property<string>("Question");

                    b.HasKey("QuestionId");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("PE3.Entities.Results", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PupilAnswer");

                    b.Property<long>("PupilId");

                    b.Property<long>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("PupilId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("PE3.Entities.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new { Id = 1L, FirstName = "Dirk", LastName = "Vandenbroucke", Login = "dvandenbroucke", Password = "teacher" },
                        new { Id = 2L, FirstName = "Evan", LastName = "Dierickx", Login = "edierickx", Password = "teacher" },
                        new { Id = 3L, FirstName = "Sam", LastName = "Verkeyen", Login = "sverkeyen", Password = "teacher" },
                        new { Id = 4L, FirstName = "Erika", LastName = "Berends", Login = "eberends", Password = "teacher" },
                        new { Id = 5L, FirstName = "Sarah", LastName = "Cramers", Login = "scramers", Password = "teacher" }
                    );
                });

            modelBuilder.Entity("PE3.Entities.ClassRoom", b =>
                {
                    b.HasOne("PE3.Entities.Teacher", "Teacher")
                        .WithOne("ClassRoom")
                        .HasForeignKey("PE3.Entities.ClassRoom", "TeacherId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PE3.Entities.Pupil", b =>
                {
                    b.HasOne("PE3.Entities.ClassRoom")
                        .WithMany("Pupils")
                        .HasForeignKey("ClassRoomId");

                    b.HasOne("PE3.Entities.Teacher")
                        .WithMany("Pupils")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("PE3.Entities.PupilRegistration", b =>
                {
                    b.HasOne("PE3.Entities.ClassRoom", "ClassRoom")
                        .WithMany()
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PE3.Entities.Pupil", "Pupil")
                        .WithMany()
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PE3.Entities.Questions", b =>
                {
                    b.HasOne("PE3.Entities.ClassRoom", "ClassRoom")
                        .WithMany()
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PE3.Entities.Results", b =>
                {
                    b.HasOne("PE3.Entities.Pupil")
                        .WithMany("Results")
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PE3.Entities.Questions")
                        .WithMany("Results")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
